[plugin]
repository = "https://github.com/Abyeon/Racingway.git"
commit = "143600800a63a94eedb8ea435a9baeba4a89d35c"
owners = ["Abyeon"]
project_path = "Racingway"
changelog = """
v0.0.6.3 [TESTING]
- Update to api 12
- Fix UI timer not resetting when going back to start
"""
