[plugin]
repository = "https://github.com/Abyeon/Racingway.git"
commit = "e9e0ba53b84e4605af522aacd7d473cab595e653"
owners = ["Abyeon"]
project_path = "Racingway"
changelog = """
v0.0.5.8 [TESTING]
- Fix routes tab using old export code
- Add timer overlay
"""
