[plugin]
repository = "https://github.com/Abyeon/Racingway.git"
commit = "07910f47d0ec9e5c5f700fff2ff8277f6dae72c8"
owners = ["Abyeon"]
project_path = "Racingway"
changelog = "Fix crash that happened when TrackOthers was enabled."
