[plugin]
repository = "https://github.com/Abyeon/Racingway.git"
commit = "0d0c8d1cd992a080423d5dd11e24988f657c50b8"
owners = ["Abyeon"]
project_path = "Racingway"
changelog = """
v0.0.4.3 [TESTING]
- Fixed crash when Track Others was enabled

Known Issues:
- Need to refresh when importing routes from clipboard
- Triggers displaying incorrectly when a portion is behind the camera
"""
