[plugin]
repository = "https://github.com/Abyeon/Racingway.git"
commit = "6720d37bd9ed6a17db61adfbf1395339aeb00740"
owners = ["Abyeon"]
project_path = "Racingway"
changelog = "Added importing/exporting"