[plugin]
repository = "https://github.com/Abyeon/Racingway.git"
commit = "144b29fd0cd18e5faa96e6ec72898e7599192158"
owners = ["Abyeon"]
project_path = "Racingway"
changelog = "Added importing/exporting"
