[plugin]
repository = "https://github.com/Abyeon/Racingway.git"
commit = "18d297fcd87d01dfcf72d797f1348ed31788ccf9"
owners = ["Abyeon"]
project_path = "Racingway"
changelog = "UI Overhaul, temporary record saving, and review player racing lines via the records tab!"
